// topicLibrary.js — 10-Year Atlassian Enterprise Content Database
// 10 pillars × 45+ topics × 15 angles = 6,750+ unique post combinations

const CONTENT_ANGLES = [
  "security implications and enterprise risks you must know",
  "performance optimization and scaling strategies",
  "automation and scripting to eliminate manual work",
  "cost optimization and licensing gotchas",
  "governance and compliance requirements",
  "migration strategy and real-world pitfalls",
  "AI integration and future platform direction",
  "advanced troubleshooting and debugging techniques",
  "undocumented behavior and insider configuration patterns",
  "enterprise architecture design decisions",
  "audit readiness and compliance reporting",
  "integration patterns with third-party enterprise tools",
  "new release breakdown: what changed and why it matters",
  "real-world failure case study and lessons learned",
  "step-by-step implementation guide for enterprise teams",
];

const PILLARS = [
  {
    name: "Atlassian Cloud Administration",
    weight: 10,
    subtopics: [
      "Jira Cloud global permissions architecture and inheritance model",
      "Confluence space permissions vs site permissions conflicts",
      "JSM project permissions and customer portal access control",
      "Atlassian Guard user provisioning and SCIM sync edge cases",
      "Organization admin vs site admin vs product admin role boundaries",
      "User management at scale: group strategies for 10,000+ users",
      "IP allowlisting and network access policies in Atlassian Cloud",
      "Atlassian Access policy enforcement across products",
      "Sandbox environment management and change isolation",
      "Release tracks: Regular vs Continuous and enterprise change control",
      "Data residency selection and compliance implications",
      "Atlassian Cloud mobile device management policies",
      "Product discovery settings and shadow IT prevention",
      "Domain verification and claiming managed accounts",
      "Multi-site architecture: when to use one org vs multiple",
      "Atlassian Admin API for bulk user and group operations",
      "Audit log analysis and suspicious activity detection",
      "License management: product access vs user tiers",
      "SSO enforcement and fallback authentication risk",
      "Confluence personal spaces governance at enterprise scale",
      "Jira global automations vs project automations scope control",
      "Notification schemes: reducing alert fatigue enterprise-wide",
      "Custom field governance: preventing field sprawl in Jira",
      "Workflow schemes and the hidden complexity of shared workflows",
      "Screen schemes and the performance cost of over-customization",
      "Project templates and how to enforce standards at scale",
      "Jira issue type hierarchy: Epic-Story-Task-Subtask best practices",
      "Confluence macros security review and allowlisting",
      "Atlassian cloud backup strategy and data export limitations",
      "User deactivation vs deletion: licensing and data implications",
      "External user management and guest access governance",
      "Atlassian Connect app permissions audit process",
      "Product admin delegation and the principle of least privilege",
      "Custom domains and CNAME configuration for Atlassian Cloud",
      "Atlassian Analytics: building org-wide governance dashboards",
      "Team-managed vs company-managed projects: governance tradeoffs",
      "Jira plans (Advanced Roadmaps) permissions and hierarchy",
      "Confluence whiteboards governance and storage management",
      "Atlassian Intelligence admin controls and data handling",
      "JSM insight / Assets schema design for enterprise CMDB",
      "Change management approval workflows in JSM at scale",
      "Service project queue management and agent workload balancing",
      "SLA configuration: clock stops, calendars, and gotchas",
      "Email domain allowlisting for Jira Service Management portals",
    ],
  },
  {
    name: "Atlassian Security & Compliance",
    weight: 10,
    subtopics: [
      "Zero trust architecture with Atlassian Guard and Okta",
      "SAML 2.0 vs OIDC for Atlassian SSO: security tradeoffs",
      "OAuth 2.0 app scopes audit: reducing attack surface",
      "GDPR right to erasure in Jira and Confluence implementation",
      "SOC 2 Type II evidence collection from Atlassian audit logs",
      "ISO 27001 controls mapping to Atlassian Cloud features",
      "HIPAA compliance considerations for Atlassian Cloud deployments",
      "PCI DSS scoping when Jira is used in payment workflows",
      "API token lifecycle management and rotation enforcement",
      "Personal access token (PAT) governance and expiry policies",
      "Atlassian Guard threat detection: impossible travel alerts",
      "Session management and token revocation in enterprise SSO",
      "Data classification and Confluence content sensitivity labels",
      "Atlassian Cloud shared responsibility model breakdown",
      "Third-party app security review before marketplace installation",
      "Forge app permission scopes and data access minimization",
      "Connect app tunnel security and egress filtering",
      "Jira field-level security for sensitive data exposure prevention",
      "Audit log retention and SIEM integration via Atlassian API",
      "Insider threat detection patterns in Atlassian audit events",
      "Privilege escalation paths in misconfigured Atlassian orgs",
      "Security incident response: locking down Atlassian in a breach",
      "Managed accounts takeover security: what admins miss",
      "Cross-product data leakage between Jira and Confluence",
      "Atlassian Trust Center: understanding shared security model",
      "Pen testing Atlassian Cloud: what you can and cannot do",
      "Security review of Confluence anonymous access settings",
      "Jira automation rule security: preventing data exfiltration",
      "Webhook security: signature verification and secret rotation",
      "Atlassian Guard Premium vs Standard: security feature gaps",
      "Shadow IT detection: unauthorized Atlassian app installations",
      "FedRAMP and government compliance for Atlassian Cloud",
      "EU data residency for GDPR-compliant Atlassian deployments",
      "Vulnerability disclosure policy for Atlassian marketplace apps",
      "Security hardening checklist for new Atlassian Cloud organizations",
      "MFA enforcement strategies and backup code governance",
      "Identity governance and access reviews with Atlassian Admin API",
      "Sensitive data in Jira descriptions: DLP strategy and tooling",
      "Atlassian Cloud encryption: at rest, in transit, key management",
      "Supply chain security for Atlassian marketplace dependencies",
    ],
  },
  {
    name: "Atlassian AI & Rovo",
    weight: 12,
    subtopics: [
      "Rovo agents: architecture, capabilities, and enterprise deployment",
      "Atlassian Intelligence vs Rovo: feature boundary and use cases",
      "AI-generated Jira issue summaries: accuracy and governance",
      "Rovo search: cross-product knowledge discovery in enterprise",
      "Building custom Rovo agents with Forge and the Rovo SDK",
      "AI governance framework for Atlassian Intelligence deployment",
      "Data handling in Atlassian AI: what gets sent to LLMs",
      "Rovo chat: security considerations for enterprise sensitive data",
      "AI-assisted sprint planning and estimation accuracy studies",
      "Confluence AI content generation: quality control workflows",
      "Atlassian Intelligence admin controls: disabling per product",
      "Rovo Goals: OKR tracking with AI-powered progress analysis",
      "AI summarization of JSM incidents for post-mortem drafts",
      "Natural language Jira queries via Rovo and search API",
      "Responsible AI adoption framework for Atlassian platform",
      "AI prompt injection risks in Rovo agent inputs",
      "Measuring AI ROI in Atlassian: productivity metrics framework",
      "Rovo workflow automation vs traditional Jira automation",
      "AI-powered duplicate detection in Jira issue creation",
      "Confluence page quality scoring with Atlassian Intelligence",
      "Rovo team member insights: privacy implications and controls",
      "AI-assisted service desk: auto-resolution rate optimization",
      "Enterprise AI adoption curve: change management for Atlassian AI",
      "Atlassian AI roadmap: what's coming and strategic implications",
      "GPT vs Atlassian Intelligence: build vs buy for enterprise",
      "AI hallucination risk management in documentation workflows",
      "Rovo connectors: integrating external knowledge sources securely",
      "AI audit trails: logging AI-generated content in Confluence",
      "Atlassian AI for non-English enterprise teams: limitations",
      "Cost model for Atlassian Intelligence at enterprise scale",
    ],
  },
  {
    name: "Forge Development & Marketplace",
    weight: 9,
    subtopics: [
      "Forge vs Connect: migration path and security architecture differences",
      "Forge storage API: key-value, entity, and remote backends",
      "Forge UI Kit 2 vs Custom UI: rendering model and performance",
      "Web triggers for webhook-like Forge endpoints: security patterns",
      "Forge scheduled triggers: reliability, idempotency, error handling",
      "Forge permissions model: minimal scopes for marketplace approval",
      "Forge remote: calling external APIs securely from sandbox",
      "Forge tunnel for local development and debugging workflow",
      "Atlassian marketplace security review process deep dive",
      "Forge rate limits and throttling strategies for enterprise apps",
      "Custom UI bridge: Forge-to-UI communication patterns",
      "Forge app versioning and zero-downtime deployment strategies",
      "Forge environment variables and secret management",
      "Building Forge apps that handle 100k+ Jira issues efficiently",
      "Forge resolver design: GraphQL-like patterns for data fetching",
      "Jira issue panel Forge app: UX patterns for power users",
      "Confluence macro Forge migration from Connect step by step",
      "Forge testing framework: unit, integration, and E2E strategies",
      "Atlassian marketplace listing optimization for discovery",
      "Forge app analytics: tracking adoption and usage patterns",
      "Multi-tenant Forge architecture for SaaS marketplace apps",
      "Forge egress allowlisting and network security controls",
      "Building AI-powered Forge apps with OpenAI/Claude integration",
      "Forge app monetization models and Atlassian billing API",
      "Common Forge app rejections and how to pass security review",
      "Forge platform limits: storage, compute, timeouts reference",
      "JSM Forge apps: custom fields and portal customization patterns",
      "Bitbucket Pipes development and publishing to marketplace",
      "Atlassian Design System components in Forge Custom UI",
      "Forge app performance profiling and optimization techniques",
    ],
  },
  {
    name: "Atlassian Release Intelligence",
    weight: 12,
    subtopics: [
      "Atlassian Cloud Weekly Release Notes analysis and impact assessment",
      "Breaking changes in Jira REST API v3: migration guide",
      "Confluence v2 REST API: what changed and deprecation timeline",
      "Atlassian deprecation policy: how to track and respond proactively",
      "Early Access Program (EAP) features and how to join strategically",
      "Atlassian roadmap: announced features and enterprise planning",
      "Jira Work Management new features for business teams",
      "JSM new feature releases: ITSM and service desk improvements",
      "Atlassian Guard Premium features added in recent releases",
      "Rovo new capabilities: monthly release breakdown",
      "Atlassian Analytics new dashboards and metrics added",
      "Bitbucket Cloud new CI/CD and pipeline features",
      "Compass new features for developer experience platform",
      "Team Anywhere features for distributed enterprise teams",
      "Atlassian platform API versioning strategy and lifecycle",
      "Feature flags in Atlassian products: what controls rollout",
      "Beta feature graduation to GA: enterprise readiness checklist",
      "Atlassian Cloud infrastructure upgrades and their impact",
      "Atlassian Jira Plans (Advanced Roadmaps) feature evolution",
      "Confluence whiteboards and visual collaboration new features",
      "Atlassian's acquisition impact on product roadmap direction",
      "Atlassian Open DevOps new integrations and partner additions",
      "Jira Product Discovery (formerly Jira Align) feature updates",
      "Atlassian Intelligence feature rollout schedule and controls",
      "JSM Assets (Insight) new schema and import capabilities",
    ],
  },
  {
    name: "Enterprise Architecture & Governance",
    weight: 9,
    subtopics: [
      "Multi-product Atlassian architecture: Jira + Confluence + JSM integration patterns",
      "High availability design for Atlassian-dependent workflows",
      "Disaster recovery planning when Atlassian is mission-critical",
      "Business continuity: Atlassian Cloud SLA vs internal requirements",
      "Enterprise information architecture in Confluence at scale",
      "Jira project portfolio governance: project proliferation control",
      "Center of Excellence (CoE) model for Atlassian platform teams",
      "Atlassian governance committee: structure and decision framework",
      "Change advisory board (CAB) implementation in JSM",
      "Configuration management database (CMDB) design in JSM Assets",
      "Atlassian as system of record: integration architecture patterns",
      "Master data management for user identities across Atlassian products",
      "Enterprise taxonomy design for Jira labels and Confluence spaces",
      "Atlassian Platform as a Service: building internal tooling on top",
      "Federated Atlassian governance for M&A integration scenarios",
      "Technology radar: Atlassian product adoption framework",
      "Atlassian ROI measurement: KPIs and executive reporting model",
      "Platform health dashboard: metrics every Atlassian admin needs",
      "Atlassian maturity model: assessing and improving platform value",
      "Enterprise search strategy: Confluence as knowledge management system",
      "Jira as workflow engine: extending beyond software development",
      "Atlassian integration hub: middleware patterns for enterprise",
      "FinOps for Atlassian: tracking spend per department/team",
      "Procurement strategy for Atlassian Enterprise licensing",
      "Platform engineering with Atlassian: golden paths and guardrails",
    ],
  },
  {
    name: "Migration & Cloud Transformation",
    weight: 9,
    subtopics: [
      "Jira Server to Cloud migration: pre-migration assessment checklist",
      "Data Center to Cloud: feature parity gaps and mitigation strategies",
      "Confluence Server migration: content quality issues and remediation",
      "Connect to Forge app migration: what the ecosystem looks like in 2026",
      "User identity migration: matching Server users to cloud managed accounts",
      "Jira project data migration using Cloud Migration Assistant",
      "Confluence space migration: large attachment handling strategies",
      "JSM migration: customer data, portals, and SLA history",
      "Bitbucket Server to Cloud migration: pipelines and LFS strategy",
      "Custom fields migration: consolidation before cloud move",
      "Workflow complexity reduction before Server-to-Cloud migration",
      "Third-party app compatibility matrix for cloud migration",
      "Server license end-of-life 2025: urgency and planning guide",
      "Data Center to Cloud cost comparison: TCO analysis methodology",
      "Phased migration strategy for large enterprise Atlassian deployments",
      "Testing cloud migration with Jira Cloud sandbox environments",
      "Post-migration validation: testing checklist for all products",
      "Rollback strategy: what to do when cloud migration fails",
      "Hybrid operation: running Server and Cloud in parallel transition",
      "Stakeholder change management for Atlassian cloud migration",
      "Performance benchmarking: Server vs Cloud for high-volume teams",
      "API migration: updating integrations from Server APIs to Cloud APIs",
      "Marketplace app gap analysis for migration readiness",
      "Atlassian Cloud Migrations team: when to engage Atlassian directly",
      "Migration factory approach for multi-instance consolidation",
    ],
  },
  {
    name: "ITSM & Service Management Excellence",
    weight: 8,
    subtopics: [
      "ITIL 4 implementation in Jira Service Management: complete mapping",
      "Incident management p1/p2/p3 escalation automation in JSM",
      "Problem management workflow design: linking incidents to root causes",
      "Change management CAB automation and approval workflow design",
      "Service catalog design: IT vs HR vs Finance service offerings",
      "SLA design patterns: business hours, priority matrices, exceptions",
      "JSM Assets (Insight) CMDB: CI types, relationships, and discovery",
      "Operational level agreements (OLA) configuration in JSM",
      "Customer satisfaction (CSAT) surveys: automation and analysis",
      "JSM virtual agent: deflection rate optimization strategies",
      "On-call scheduling integration with JSM incidents via PagerDuty",
      "Major incident management war room process in JSM",
      "Service desk knowledge base optimization for self-service",
      "JSM portal branding and customization for enterprise white-labeling",
      "Multi-team incident management: escalation and handoff patterns",
      "Post-incident review (PIR) workflow automation in JSM",
      "JSM reporting: SLA compliance, agent performance dashboards",
      "Request fulfillment automation: provisioning workflows via JSM",
      "JSM email channel: spam filtering and routing configuration",
      "Enterprise service management: extending JSM beyond IT",
      "Jira Service Management for HR service delivery",
      "Facilities management and real estate requests in JSM",
      "Legal request management workflow design in JSM",
      "JSM Approvals: multi-level approval chains and delegation",
      "Proactive alerting: monitoring integration creating JSM tickets",
    ],
  },
  {
    name: "DevOps & Platform Engineering",
    weight: 8,
    subtopics: [
      "Bitbucket Pipelines vs GitHub Actions: enterprise decision framework",
      "Jira + Bitbucket integration: commit-to-deployment traceability",
      "Atlassian Open DevOps: assembling the complete toolchain",
      "Compass developer portal: service catalog and scorecards setup",
      "Deployment frequency tracking with Jira and Bitbucket metrics",
      "DORA metrics implementation across Atlassian toolchain",
      "Bitbucket Pipelines parallel steps for faster build times",
      "Jira automation for DevOps: auto-transition on PR merge",
      "Feature flag integration with Jira using LaunchDarkly or Unleash",
      "Incident-to-code tracing: linking JSM incidents to Bitbucket commits",
      "Developer experience metrics: tracking cycle time in Jira",
      "Internal developer platform (IDP) built on Atlassian stack",
      "Atlassian for SRE: reliability tracking and SLO management",
      "Bitbucket branch permissions and protected branch strategies",
      "Code review quality metrics via Bitbucket pull request analytics",
      "Jira sprint metrics: velocity, predictability, and forecasting",
      "Dependency management visualization in Jira Advanced Roadmaps",
      "GitOps workflow integration with Jira deployment tracking",
      "Security scanning in Bitbucket Pipelines: SAST/DAST patterns",
      "Container registry integration with Bitbucket Pipelines",
      "Monorepo strategy with Bitbucket Pipelines for microservices",
      "Platform engineering golden paths: Jira project templates",
      "Developer onboarding automation via Jira and Confluence",
      "Atlassian Data Lake for engineering analytics and BI",
      "Team topology mapping with Compass and Jira team configuration",
    ],
  },
  {
    name: "Atlassian Licensing, Billing & FinOps",
    weight: 8,
    subtopics: [
      "Atlassian Cloud pricing tiers: Free vs Standard vs Premium vs Enterprise",
      "Atlassian Enterprise license: what you actually get and when it's worth it",
      "User tier billing: how monthly active users (MAU) are calculated",
      "Atlassian Guard pricing and bundling with product subscriptions",
      "License optimization: identifying inactive users consuming paid seats",
      "Atlassian subscription renewal strategy: negotiation leverage points",
      "Multi-product bundle discounts: Atlassian platform pricing strategy",
      "Atlassian annual vs monthly billing tradeoffs for enterprises",
      "FinOps for Atlassian: chargeback model per department",
      "Atlassian marketplace app licensing: per-user vs flat fee analysis",
      "True-up billing and avoiding surprise costs in Atlassian Cloud",
      "Atlassian partner reseller vs direct purchase: cost comparison",
      "Rovo pricing model and ROI justification for enterprise",
      "Atlassian Intelligence add-on costs and value assessment",
      "Atlassian Flexible Deployment: understanding the new licensing model",
      "Cloud site consolidation to reduce duplicate licensing costs",
      "Free product tier governance: preventing unauthorized team sprawl",
      "Atlassian for startups, academic, and nonprofit discounts",
      "License audit workflow: quarterly user access review process",
      "Atlassian billing API: automating cost reporting and forecasting",
      "Marketplace app cost governance: approval workflow for new apps",
      "Atlassian Data Center to Cloud TCO comparison methodology",
      "Executive budget justification template for Atlassian Enterprise",
      "Atlassian MSA negotiation: key clauses enterprise procurement needs",
      "Cost alert thresholds and budget tracking for Atlassian spend",
    ],
  },
];

module.exports = { PILLARS, CONTENT_ANGLES };
